spring:
  application:
    name: Twitter-Backend
  datasource:
    url: jdbc:postgresql://localhost:5432/twitter
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update

